Resources api
aSehat/MITR-Project pull request #10
Opened 2020-11-02 15:11 UTC by KristoferKwan

2020-11-03 17:23 UTC, emiliearenkid requested changes
Remove the SignupHeader.js file. I made that initially before we made the general header and it no longer needs to be in the project.
The Login and Signup links no longer work.

This isn't a big thing at all but when I highlighted a section, the popup for creating a resources or adding a property, that box popped up at the top of my highlight but the actual modal to fill out the info popped up at the bottom of my highlight and I had to scroll to get the data. As I said, not a huge thing by any means but ideally sticking to one or would be great on the visual side. 

I can also create properties that don't have a resource instantiation and I can just create resources with empty fields, which I'm not sure should be allowed to happen.

Otherwise, I think this looks and functions great!

2020-11-03 17:33 UTC, KristoferKwan commented
> _No description provided._

2020-11-03 17:35 UTC, KristoferKwan commented
> Remove the SignupHeader.js file. I made that initially before we made the general header and it no longer needs to be in the project.
> The Login and Signup links no longer work.
> 
> This isn't a big thing at all but when I highlighted a section, the popup for creating a resources or adding a property, that box popped up at the top of my highlight but the actual modal to fill out the info popped up at the bottom of my highlight and I had to scroll to get the data. As I said, not a huge thing by any means but ideally sticking to one or would be great on the visual side.
> 
> I can also create properties that don't have a resource instantiation and I can just create resources with empty fields, which I'm not sure should be allowed to happen.
> 
> Otherwise, I think this looks and functions great!

Yea makes sense. I delete the login and Signup. I agree the scroll thing isn't super great, though I haven't gotten around to changing it (as that was the way it was in the demo). Also form validation doesn't yet exist in resource and property forms -- will work on adding this in future changes on differ branch.

2020-11-06 02:58 UTC, tremag approved these changes

2020-11-06 02:59 UTC, merged